#http://www.thejazzpage.de/index1.html

"""
I decided it would be easier to generate a list of the names
of the files in the browser console than with beautiful soup
(because of the weird nature of the website).

to reproduce:

//gather filenames

let a = document.getElementsByTagName("a");
let files = "";
[...a].forEach(e => {
	let slash = e.href.lastIndexOf("/");
	if(slash != -1)
	{
		let basename = e.href.substring(slash+1);
		if(basename.includes(".mid"))
			files += basename + "\n"
	}
}

//save filenames

let blob = new Blob([files]);
let url = URL.createObjectURL(blob);
let file = document.createElement("a");
file.download = "songnames.txt";
file.href = url;
document.body.appendChild(file);
file.click();
file.remove();
URL.revokeObjectURL(url);

That was quirky...
Then I used multiline editing in Sublime Text to add quotes and
commas to each file name, and voila.
"""

SONG_TITLES = ["11pmtheme.mid",
"16goingon17.mid",
"20thcenturystomp.mid",
"2ndtime.mid",
"4thAvenueTheme.mid",
"felicid.MID",
"AFoggyD.MID",
"agfih2find.mid",
"tunisia2.mid",
"tunisia.mid",
"Aintmisb.mid",
"ALICEINW.MID",
"allblues.mid",
"AllOfMe2.mid",
"AllOfMe2.mid",
"alltheth.mid",
"Allthing.mid",
"IALikeBeingInLove.mid",
"alone.mid",
"Alonetog.mid",
"along.mid",
"atIknew.mid",
"angeleyes.mid",
"angeleye.mid",
"angela.mid",
"Anthropology.mid",
"auprvave.mid",
"autleave.mid",
"AutumnL.mid",
"autumn_leaves.MID",
"Bach3B.MID",
"Basiervg.mid",
"bayou.mid",
"bbblues.mid",
"beacon.mid",
"beale.mid",
"Beautiful_Love.mid",
"Berniestune.mid",
"bethlehem.mid",
"bdazhed.mid",
"bewitched.mid",
"BigMess.mid",
"bigtime.mid",
"billiesb.mid",
"birdland.mid",
"Blknrcs.mid",
"bbossaje.mid",
"BLBOSSA.MID",
"Blue_In_Green.mid",
"BlueMonk.mid",
"blumonk.mid",
"Bluenboo.mid",
"BlueRondo.mid",
"BlueTrain.mid",
"bl4alice.mid",
"Blues4Basie.mid",
"blues4npage.mid",
"BluesForTrane.mid",
"blueswalk.mid",
"bluesette.mid",
"Bodysoul.mid",
"BodyAndSoul.mid",
"BodySoul_tb.MID",
"bolivia.mid",
"Bop_OnTR.mid",
"BORGAN_Lues.mid",
"Born2BBlue.mid",
"brasil.mid",
"Breezin_.mid",
"broadwa2.mid",
"BPowell.mid",
"budo.mid",
"Bye_ByeG.MID",
"cjamblusx.mid",
"CannonBBl.mid",
"cantalope.mid",
"caravan.mid",
"carchase.mid",
"CarnHallBounce.mid",
"Cat_Walk.mid",
"CentralParkWest.mid",
"Chameleon.mid",
"chega.mid",
"Chega_de_saudade.mid",
"Cheek_To_Cheek.mid",
"chsticks.mid",
"cherokee.mid",
"CHIM.mid",
"xmas.mid",
"chromBlinF.mid",
"CityGate.mid",
"CleanSweep.mid",
"comerain.mid",
"comerain2.MID",
"conalma.mid",
"Corner_pocket.mid",
"CottonG.MID",
"criss-cross.mid",
"Cute.mid",
"Datdere2.mid",
"daybyday.mid",
"daybyday2.mid",
"DaysOf.mid",
"decoy.mid",
"Desafinado78.mid",
"dig.mid",
"NothinG.MID",
"DolphinDance.mid",
"don-lee2.mid",
"DATDoor.mid",
"AroundVG.MID",
"DstMeT.mid",
"doxy.mid",
"eastofthesun.mid",
"EndOfSummer.mid",
"escucha.mid",
"eyeotbeh.mid",
"FarWes.MID",
"FastBluesJam.mid",
"fever2.mid",
"flybynight.mid",
"Footprints_R.mid",
"foreplayx.mid",
"four2.mid",
"4brosrvg.mid",
"4on6.mid",
"FreckleFace.mid",
"Freedom_At_Midnight.mid",
"funkallero.mid",
"GentleRain.mid",
"Georgia.mid",
"gsteps.mid",
"goodbait.mid",
"GrooveYard.mid",
"grooving_hard.mid",
"groovn.mid",
"guardian1.mid",
"halfzware_shag.mid",
"HaNiceDayG.MID",
"HaveUheard.mid",
"HaveUMMsJ.mid",
"hayBurner.mid",
"heavy.mid",
"Heat.mid",
"helpme.mid",
"Here.mid",
"Hifly4.mid",
"honey.MID",
"hornfunk.mid",
"Howhigh.mid",
"HowIns.mid",
"HOW.mid",
"HushABye.mid",
"IConcOnY.mid",
"IConcOnYou.mid",
"ICWABook.mid",
"Idkwhtime.mid",
"gotrhytm.mid",
"IGotRhythm.MID",
"ineverknew.mid",
"ISaidItbefore.mid",
"I_Wont_Dance_R.mid",
"If_bell.mid",
"Takerv3g.mid",
"world.mid",
"accustumed.mid",
"IGrownAcc2HF.mid",
"Impressions.mid",
"Woods1G.MID",
"sentmood.mid",
"in_love_with_night.mid",
"intheevening.mid",
"sweet.mid",
"INVITATION.mid",
"israel.mid",
"idmathing.mid",
"itsallright.mid",
"itsjusttalk.mid",
"jaco.mid",
"jordu2.mid",
"joshua.mid",
"JoySpring.mid",
"joyed.mid",
"Justfren.mid",
"Justjazz.mid",
"JustOneG.MID",
"KathysWaltz.mid",
"kicker2.mid",
"killerjoe.mid",
"FiestaRG.MID",
"LauraG.mid",
"lazybird.mid",
"LibertyCity.mid",
"LilDarlin.MID",
"LittlePixieG.MID",
"Lovehere.mid",
"LoveMachine.mid",
"Lovewalkedin.mid",
"Lover.mid",
"LBirdland.mid",
"lullaby.mid",
"Lulu.MID",
"LushLife.mid",
"Mack.mid",
"mvoyage.mid",
"orpheus.mid",
"carnival.MID",
"Orfeo.mid",
"maisquenada.mid",
"Mannix.mid",
"manteca.mid",
"MapleLeafRag.mid",
"meantome.mid",
"medit.mid",
"MembersOnly.mid",
"menilmuche.mid",
"minorsw.mid",
"misty.MID",
"moanin.mid",
"modusinterr.mid",
"Mnksmd.mid",
"move.mid",
"mwv_blues.mid",
"myfavts.mid",
"favorite.MID",
"myfoolheart.mid",
"funnyval2.MID",
"my1aonly.mid",
"naima95.mid",
"NARDIS.mid",
"nardis2.mid",
"Nardisg.mid",
"NETBOP.MID",
"Nicadream.mid",
"nica.mid",
"niteday.mid",
"NoMoreBlues.mid",
"nowsthet.mid",
"nuages.mid",
"Nutville.mid",
"olddevilmoon.mid",
"dolphnst.mid",
"ontheotherhand.mid",
"one4hellen.mid",
"onenote.mid",
"OpFunk.mid",
"OrthlgyG.MID",
"OurLove.mid",
"OurLove_x.mid",
"outwhere.MID",
"paladium.mid",
"palco.mid",
"Passanova.mid",
"peace.mid",
"pennies.mid",
"people.mid",
"pep.mid",
"perissc.mid",
"petite_fleur.mid",
"phasedance.mid",
"pinebark.mid",
"pinkp.mid",
"poinciana.mid",
"polkadot.MID",
"PorgyG.MID",
"prelude.mid",
"quick.mid",
"RhyANing.mid",
"riofunk.mid",
"RioSamba.MID",
"RockMeBaby.mid",
"rollem.mid",
"romwargm.mid",
"roofgdn2.mid",
"rndmngt.mid",
"Route66G.MID",
"rumble.mid",
"peanutsg.mid",
"Samba_do_Aviao.mid",
"santa.mid",
"SatinDol.mid",
"satin_doll.mid",
"ScrapleG.MID",
"secretlove.mid",
"Senor2.mid",
"serialnumber.mid",
"seven.mid",
"shawnuff.mid",
"shiny.mid",
"sinceIfell.mid",
"SingSing.mid",
"Sodanco.mid",
"sowhat1.mid",
"softly.mid",
"solar.mid",
"someday.mid",
"someday2.mid",
"someband.mid",
"sonata4vc.mid",
"songforbilbao.mid",
"songfor.mid",
"soon.mid",
"SophisticatedLady.mid",
"SPAIN2.MID",
"SpLACh.mid",
"speaklo3.mid",
"spknoevl.mid",
"ST_LOUIS.MID",
"thomas.mid",
"st_vit2.mid",
"stella2.mid",
"stiltime.mid",
"stolen.mid",
"StWeather.mid",
"snochase.mid",
"straight.mid",
"summert.MID",
"sushi.mid",
"sweetgb3.mid",
"SweetSixteen.mid",
"Swing42.mid",
"Atrain.mid",
"atrain2.mid",
"TakinAC.mid",
"Teentown.mid",
"tempusfugit.mid",
"tenderly.mid",
"thechicken.mid",
"ipanema.MID",
"HeatsOnG.MID",
"TheJoke.MID",
"TheManILove.mid",
"TheOddCpl.mid",
"thiscantbelove.mid",
"timeaftertime.mid",
"tp.mid",
"toss_up.mid",
"Triste.mid",
"tristeza.mid",
"tutu.mid",
"Up_With_The_Lark.mid",
"Vegaswk.mid",
"veryearly.mid",
"WALTZ.mid",
"WWHappens.mid",
"Wave3.mid",
"weasel.mid",
"wellyoun.mid",
"whatsnew.MID",
"wylhg.mid",
"whisper.mid",
"whispernot.mid",
"Whocaniturnto.mid",
"windsinterpl.mid",
"WoodynYou.MID",
"XmasSong.mid",
"xtracrispy.mid",
"YardBrdG.MID",
"younight.mid",
"sunshine2.MID",
"yuarrest.mid",
"youstep.mid",
"youdbe.mid",
"YBSN2CH2.mid",
"zanzibar.mid",
"Zip-A-Dee-Doo-Dah.mid"]

import requests
import urllib

USER_AGENT = 'curl/7.54.0'
HEADERS    = {'user-agent' : USER_AGENT}

url = "http://www.thejazzpage.de/sounds/"
n = 0
for song in SONG_TITLES:
	urllib.request.urlretrieve(url + song, song)
	print("Downloading", str(n), end="\r")
	n+=1
